title = "デイトレード戦略と日々の記録"
baseURL = 'https://xn--pbty99adk8a.com/'

# This is what goes in <html lang="">
languageCode = 'ja-jp'

# This defines how dates are formatted
defaultContentLanguage = "ja"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
#[module]
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  # workspace = "hugo-blog-awesome.work"
  #[module.hugoVersion]
    #extended = true
    #min = "0.87.0"
  #[[module.imports]]
    #path = "github.com/hugo-sid/hugo-blog-awesome"
    #disable = false

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  [services.disqus]
    shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 1 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[params]
  sitename = "宝水香のホームページ"
  defaultColor = "light"
  description = "デイトレード戦略と日々の記録"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  dateFormat = "2006年01月02日"
  rssFeedDescription = "summary"

[params.author]
    avatar = "pikumin.jpg" 
    intro = "宝水香のホームページ"
    name = "Kaoru Hosui" 
    description = "デイトレード戦略と日々の記録"
  
[params.webmanifest] 
  name = "Kaoru Hosui"
  short_name = "Kaoru"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "x"
url = "https://x.com/Kaoru_trader"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@hosui-kaoru-worldchanger" 

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

# グローバルなメニュー設定
[menu]
  [[menu.main]]
    pageRef="/"
    name = 'ホーム'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = '投稿'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = '自己紹介'
    url = '/about/'
    weight = 30