[build]
  command = "hugo"
  publish = "public"
  functions = "netlify/functions"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/basic-auth"
  status = 200
  force = true
  conditions = { "x-netlify-auth-success" = "true" }