[[redirects]]
  from = "/*"
  to = "/.netlify/functions/basic-auth"
  status = 200
  force = true

[[redirects]]
  from = "/authenticated/*"
  to = "https://xn--pbty99adk8a.com/:splat"
  status = 302
  force = true